import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata } from './metadata-parser-base';

/**
 * Parser for the PrusaSlicer comment dialect, shared by the whole family of
 * PrusaSlicer-derived slicers (SuperSlicer, OrcaSlicer, BambuStudio).
 *
 * Layer comment format:
 * ;LAYER_CHANGE
 * ;Z:0.3
 * ;HEIGHT:0.3
 *
 * Bambu/Orca additionally emit explicit layer indices:
 * ;LAYER:12
 */
export class PrusaFamilyMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'PrusaFamily';

  /** Generator names reported verbatim when found in the header comments */
  private static readonly KNOWN_SLICERS = ['PrusaSlicer', 'SuperSlicer', 'OrcaSlicer', 'BambuStudio'];

  readonly identificationPatterns = [
    /generated by PrusaSlicer/i,
    /generated by SuperSlicer/i,
    /generated by OrcaSlicer/i,
    /generated by BambuStudio/i,
    /LAYER_CHANGE/,
    /BEFORE_LAYER_CHANGE/,
    /AFTER_LAYER_CHANGE/,
    /PrusaSlicer/i,
    /SuperSlicer/i,
    /OrcaSlicer/i,
    /BambuStudio/i,
    /Bambu Lab/i
  ];

  /**
   * Reports the specific family member named in the header comments, falling
   * back to the generic family name when only the shared LAYER_CHANGE dialect
   * identified the file.
   * @param commentCommands - Array of gcode commands with comments
   * @returns The specific slicer name, or 'PrusaFamily' when unknown
   */
  detectSlicerName(commentCommands: GCodeCommand[]): string {
    const sample = commentCommands.length > 200 ? commentCommands.slice(0, 200) : commentCommands;
    for (const name of PrusaFamilyMetadataParser.KNOWN_SLICERS) {
      if (sample.some((cmd) => cmd.comment!.includes(name))) {
        return name;
      }
    }
    return this.slicerName;
  }

  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let currentZ: number | undefined;
    let currentHeight: number | undefined;
    let currentLineIndex = -1;
    let currentExplicitLayerIndex: number | undefined;
    let autoLayerIndex = 0;
    let inLayerChange = false;

    const pushCurrentLayer = (): void => {
      if (currentLineIndex < 0) return;
      layers.push({
        layerIndex: currentExplicitLayerIndex ?? autoLayerIndex,
        z: currentZ,
        height: currentHeight,
        lineIndex: currentLineIndex
      });
      autoLayerIndex++;
    };

    for (let i = 0; i < commands.length; i++) {
      const comment = commands[i].comment;
      if (!comment) continue;

      if (
        comment.includes('LAYER_CHANGE') &&
        !comment.includes('BEFORE_LAYER_CHANGE') &&
        !comment.includes('AFTER_LAYER_CHANGE')
      ) {
        pushCurrentLayer();
        currentLineIndex = i;
        currentZ = undefined;
        currentHeight = undefined;
        currentExplicitLayerIndex = undefined;
        inLayerChange = true;
        continue;
      }

      if (!inLayerChange) continue;

      if (comment.startsWith('Z:')) {
        const val = parseFloat(comment.slice(2));
        if (!isNaN(val)) currentZ = val;
        continue;
      }

      if (comment.startsWith('HEIGHT:')) {
        const val = parseFloat(comment.slice(7));
        if (!isNaN(val)) currentHeight = val;
        continue;
      }

      const layerMatch = comment.match(/^LAYER:(\d+)/);
      if (layerMatch) {
        currentExplicitLayerIndex = parseInt(layerMatch[1]);
      }
    }

    pushCurrentLayer();
    return layers;
  }
}
