import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata } from './metadata-parser-base';

export class PrusaFamilyMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'PrusaFamily';

  readonly identificationPatterns = [
    /generated by SuperSlicer/i,
    /generated by OrcaSlicer/i,
    /generated by BambuStudio/i,
    /LAYER_CHANGE/,
    /BEFORE_LAYER_CHANGE/,
    /AFTER_LAYER_CHANGE/,
    /SuperSlicer/i,
    /OrcaSlicer/i,
    /BambuStudio/i,
    /Bambu Lab/i
  ];

  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let currentZ: number | undefined;
    let currentHeight: number | undefined;
    let currentLineIndex = -1;
    let currentExplicitLayerIndex: number | undefined;
    let autoLayerIndex = 0;
    let inLayerChange = false;

    const pushCurrentLayer = (): void => {
      if (currentLineIndex < 0) return;
      layers.push({
        layerIndex: currentExplicitLayerIndex ?? autoLayerIndex,
        z: currentZ,
        height: currentHeight,
        lineIndex: currentLineIndex
      });
      autoLayerIndex++;
    };

    for (let i = 0; i < commands.length; i++) {
      const comment = commands[i].comment;
      if (!comment) continue;

      if (
        comment.includes('LAYER_CHANGE') &&
        !comment.includes('BEFORE_LAYER_CHANGE') &&
        !comment.includes('AFTER_LAYER_CHANGE')
      ) {
        pushCurrentLayer();
        currentLineIndex = i;
        currentZ = undefined;
        currentHeight = undefined;
        currentExplicitLayerIndex = undefined;
        inLayerChange = true;
        continue;
      }

      if (!inLayerChange) continue;

      if (comment.startsWith('Z:')) {
        const val = parseFloat(comment.slice(2));
        if (!isNaN(val)) currentZ = val;
        continue;
      }

      if (comment.startsWith('HEIGHT:')) {
        const val = parseFloat(comment.slice(7));
        if (!isNaN(val)) currentHeight = val;
        continue;
      }

      const layerMatch = comment.match(/^LAYER:(\d+)/);
      if (layerMatch) {
        currentExplicitLayerIndex = parseInt(layerMatch[1]);
      }
    }

    pushCurrentLayer();
    return layers;
  }
}
