import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata } from './metadata-parser-base';

/**
 * Parser for PrusaSlicer metadata comments
 *
 * PrusaSlicer uses the following layer comment format:
 * ;LAYER_CHANGE
 * ;Z:0.3
 * ;HEIGHT:0.3
 */
export class PrusaSlicerMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'PrusaSlicer';

  readonly identificationPatterns = [
    /LAYER_CHANGE/,
    /generated by PrusaSlicer/i,
    /BEFORE_LAYER_CHANGE/,
    /AFTER_LAYER_CHANGE/
  ];

  /**
   * Parses layer metadata from PrusaSlicer comments
   * @param commands - Array of gcode commands with comments
   * @returns Array of layer metadata
   */
  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let currentLayer: Partial<LayerMetadata> = {};
    let layerIndex = 0;

    commands.forEach((command, lineIndex) => {
      if (!command.comment) return;

      const comment = command.comment.trim();

      // Check for layer change marker
      if (comment === 'LAYER_CHANGE') {
        // Save previous layer if it has data
        if (currentLayer.lineIndex !== undefined) {
          layers.push({
            layerIndex: layerIndex - 1,
            ...currentLayer
          } as LayerMetadata);
        }

        // Start new layer
        currentLayer = { lineIndex };
        layerIndex++;
      }
      // Extract Z position
      else if (comment.startsWith('Z:')) {
        const zMatch = comment.match(/Z:([\d.-]+)/);
        if (zMatch) {
          currentLayer.z = parseFloat(zMatch[1]);
        }
      }
      // Extract layer height
      else if (comment.startsWith('HEIGHT:')) {
        const heightMatch = comment.match(/HEIGHT:([\d.-]+)/);
        if (heightMatch) {
          currentLayer.height = parseFloat(heightMatch[1]);
        }
      }
    });

    // Don't forget the last layer
    if (currentLayer.lineIndex !== undefined) {
      layers.push({
        layerIndex: layerIndex - 1,
        ...currentLayer
      } as LayerMetadata);
    }

    return layers;
  }
}
