import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata, ExtrusionDimensionMetadata } from './metadata-parser-base';

/**
 * Parser for the PrusaSlicer comment dialect, shared by the whole family of
 * PrusaSlicer-derived slicers (SuperSlicer, OrcaSlicer, BambuStudio).
 *
 * Layer comment format:
 * ;LAYER_CHANGE
 * ;Z:0.3
 * ;HEIGHT:0.3
 *
 * Bambu/Orca additionally emit explicit layer indices:
 * ;LAYER:12
 *
 * Extrusion dimension comments, announcing the width and height of the
 * extrusions that follow (many per layer):
 * ;WIDTH:0.45
 * ;HEIGHT:0.16
 */
export class PrusaFamilyMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'PrusaFamily';

  /** Generator names reported verbatim when found in the header comments */
  private static readonly KNOWN_SLICERS = ['PrusaSlicer', 'SuperSlicer', 'OrcaSlicer', 'BambuStudio'];

  /**
   * Matches the standalone dimension comments (`WIDTH:0.45`, `HEIGHT:0.16`;
   * the parser hands comments over pre-trimmed and without the `;`).
   * Whitespace around the colon and value is tolerated, but the value must be
   * a plain decimal number — trailing junk (`0.45mm`) rejects the line rather
   * than being silently truncated by parseFloat. `\d+(?:\.\d+)?` is written
   * without adjacent ambiguous digit runs on purpose: `\d*\.?\d+` backtracks
   * polynomially on long digit strings with a non-matching tail
   * (js/polynomial-redos), this form fails in linear time.
   * @remarks
   * Deliberately capture-free: a slicer emits one of these per extrusion
   * (33,168 in the bundled 3DBenchy), and the match arrays cost more than
   * recovering the two values by hand — the leading letter already says which
   * dimension it is, and everything after the colon is the number.
   */
  private static readonly DIMENSION_PATTERN = /^(?:WIDTH|HEIGHT)\s*:\s*\d+(?:\.\d+)?\s*$/;

  /** Character code of `W`; a matched comment starting with it announces a width */
  private static readonly W_CHAR_CODE = 87;

  /** Character code of `H`, the only other letter a dimension comment can start with */
  private static readonly H_CHAR_CODE = 72;

  readonly identificationPatterns = [
    /generated by PrusaSlicer/i,
    /generated by SuperSlicer/i,
    /generated by OrcaSlicer/i,
    /generated by BambuStudio/i,
    /LAYER_CHANGE/,
    /BEFORE_LAYER_CHANGE/,
    /AFTER_LAYER_CHANGE/,
    /PrusaSlicer/i,
    /SuperSlicer/i,
    /OrcaSlicer/i,
    /BambuStudio/i,
    /Bambu Lab/i
  ];

  /**
   * Reports the specific family member named in the header comments, falling
   * back to the generic family name when only the shared LAYER_CHANGE dialect
   * identified the file.
   * @param commentCommands - Array of gcode commands with comments
   * @returns The specific slicer name, or 'PrusaFamily' when unknown
   */
  detectSlicerName(commentCommands: GCodeCommand[]): string {
    const sample = commentCommands.length > 200 ? commentCommands.slice(0, 200) : commentCommands;
    for (const name of PrusaFamilyMetadataParser.KNOWN_SLICERS) {
      if (sample.some((cmd) => cmd.comment!.includes(name))) {
        return name;
      }
    }
    return this.slicerName;
  }

  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let currentZ: number | undefined;
    let currentHeight: number | undefined;
    let currentLineIndex = -1;
    let currentExplicitLayerIndex: number | undefined;
    let autoLayerIndex = 0;
    let inLayerChange = false;

    const pushCurrentLayer = (): void => {
      if (currentLineIndex < 0) return;
      layers.push({
        layerIndex: currentExplicitLayerIndex ?? autoLayerIndex,
        z: currentZ,
        height: currentHeight,
        lineIndex: currentLineIndex
      });
      autoLayerIndex++;
    };

    for (let i = 0; i < commands.length; i++) {
      const comment = commands[i].comment;
      if (!comment) continue;

      if (
        comment.includes('LAYER_CHANGE') &&
        !comment.includes('BEFORE_LAYER_CHANGE') &&
        !comment.includes('AFTER_LAYER_CHANGE')
      ) {
        pushCurrentLayer();
        currentLineIndex = i;
        currentZ = undefined;
        currentHeight = undefined;
        currentExplicitLayerIndex = undefined;
        inLayerChange = true;
        continue;
      }

      if (!inLayerChange) continue;

      if (comment.startsWith('Z:')) {
        const val = parseFloat(comment.slice(2));
        if (!isNaN(val)) currentZ = val;
        continue;
      }

      if (comment.startsWith('HEIGHT:')) {
        const val = parseFloat(comment.slice(7));
        if (!isNaN(val)) currentHeight = val;
        continue;
      }

      const layerMatch = comment.match(/^LAYER:(\d+)/);
      if (layerMatch) {
        currentExplicitLayerIndex = parseInt(layerMatch[1]);
      }
    }

    pushCurrentLayer();
    return layers;
  }

  /**
   * Parses `;WIDTH:` / `;HEIGHT:` extrusion dimension comments
   * @param commands - Array of gcode commands with comments
   * @returns One event per dimension comment, in line order
   * @remarks
   * Every `HEIGHT:` line is reported, including the ones inside a
   * `LAYER_CHANGE` block: there it doubles as the layer's height (see
   * parseLayerMetadata) and as the line height of the paths that follow,
   * which is exactly how adaptive layer height reaches individual paths.
   * Non-numeric and non-positive values are ignored.
   */
  parseExtrusionDimensions(commands: GCodeCommand[]): ExtrusionDimensionMetadata[] {
    const dimensions: ExtrusionDimensionMetadata[] = [];

    for (let i = 0; i < commands.length; i++) {
      const comment = commands[i].comment;
      if (!comment) continue;

      // Rejects the other comments on their first character, before the
      // pattern runs: the whole file's comments pass through here.
      const firstCharCode = comment.charCodeAt(0);
      if (
        firstCharCode !== PrusaFamilyMetadataParser.W_CHAR_CODE &&
        firstCharCode !== PrusaFamilyMetadataParser.H_CHAR_CODE
      ) {
        continue;
      }
      if (!PrusaFamilyMetadataParser.DIMENSION_PATTERN.test(comment)) continue;

      // The pattern has already vouched for the shape, so everything past the
      // colon is the number, and parseFloat skips the whitespace around it.
      const value = parseFloat(comment.slice(comment.indexOf(':') + 1));
      if (!Number.isFinite(value) || value <= 0) continue;

      if (firstCharCode === PrusaFamilyMetadataParser.W_CHAR_CODE) {
        dimensions.push({ width: value, lineIndex: i });
      } else {
        dimensions.push({ height: value, lineIndex: i });
      }
    }

    return dimensions;
  }
}
