import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata } from './metadata-parser-base';

export class Simplify3DMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'Simplify3D';

  readonly identificationPatterns = [
    /Generated by Simplify3D/i,
    /Simplify3D/i,
    /layer \d+, Z = [\d.-]+/i,
    /Layer count:/i
  ];

  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let hasStandardFormat = false;

    // First pass: check if we have any standard format
    for (const command of commands) {
      if (command.comment && /layer ([^,]+), Z = ([^\s;]+)/i.test(command.comment)) {
        hasStandardFormat = true;
        break;
      }
    }

    for (let i = 0; i < commands.length; i++) {
      const command = commands[i];

      if (!command.comment) continue;

      // Detect layer format: "; layer 1, Z = 0.2" or handle malformed ones
      const layerMatch = command.comment.match(/layer ([^,]+), Z = ([^\s;]+)/i);
      if (layerMatch) {
        const layerIndex = parseInt(layerMatch[1]);
        const z = parseFloat(layerMatch[2]);

        // Calculate height from previous layer if available
        let height: number | undefined;
        if (layers.length > 0 && layers[layers.length - 1].z !== undefined) {
          height = Math.round((z - layers[layers.length - 1].z!) * 10000) / 10000; // Round to avoid floating point precision issues
        }

        layers.push({
          layerIndex,
          z,
          height,
          lineIndex: i
        });
      }

      // Alternative format: "; Layer Z = 0.3" - only if no standard format exists
      const altLayerMatch = command.comment.match(/Layer Z = ([^\s;]+)/i);
      if (altLayerMatch && !hasStandardFormat) {
        const z = parseFloat(altLayerMatch[1]);

        // Calculate height from previous layer if available
        let height: number | undefined;
        if (layers.length > 0 && layers[layers.length - 1].z !== undefined) {
          height = Math.round((z - layers[layers.length - 1].z!) * 10000) / 10000; // Round to avoid floating point precision issues
        }

        layers.push({
          layerIndex: layers.length,
          z,
          height,
          lineIndex: i
        });
      }
    }

    return layers;
  }
}
