import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata } from './metadata-parser-base';

export class Simplify3DMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'Simplify3D';

  readonly identificationPatterns = [
    /Generated by Simplify3D/i,
    /Simplify3D/i,
    /^layer \d+, Z = [-\d.]+/i,
    /Layer count:/i
  ];

  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let formatLocked: 'standard' | 'alt' | null = null;

    for (let i = 0; i < commands.length; i++) {
      const { comment } = commands[i];
      if (!comment) continue;

      const standard = comment.match(/^layer (\d+), Z = ([-\d.]+)/i);
      if (standard) {
        formatLocked = 'standard';
        const layerIndex = parseInt(standard[1]);
        const z = parseFloat(standard[2]);
        const prev = layers[layers.length - 1];
        const height =
          prev?.z !== undefined ? Math.round((z - prev.z) * 10000) / 10000 : undefined;
        layers.push({ layerIndex, z, height, lineIndex: i });
        continue;
      }

      if (formatLocked !== 'standard') {
        const alt = comment.match(/^Layer Z = ([-\d.]+)/i);
        if (alt) {
          formatLocked = 'alt';
          const z = parseFloat(alt[1]);
          const prev = layers[layers.length - 1];
          const height =
            prev?.z !== undefined ? Math.round((z - prev.z) * 10000) / 10000 : undefined;
          layers.push({ layerIndex: layers.length, z, height, lineIndex: i });
        }
      }
    }

    return layers;
  }
}
