import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata } from './metadata-parser-base';

export class Slic3rMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'Slic3r';

  readonly identificationPatterns = [
    /Generated by Slic3r/i,
    /Slic3r \d+\./i,
    /move to next layer \(\d+\)/i,
    /layer_z = [\d.-]+/i,
    /Slic3r PE/i
  ];

  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let hasMoveToNextLayer = false;

    // First pass: check if we have move to next layer format
    for (const command of commands) {
      if (command.comment && /move to next layer \(\d+\)/i.test(command.comment)) {
        hasMoveToNextLayer = true;
        break;
      }
    }

    for (let i = 0; i < commands.length; i++) {
      const command = commands[i];

      if (!command.comment) continue;

      // Detect layer format: "; move to next layer (1)" - handle malformed layer numbers
      const layerMatch = command.comment.match(/move to next layer \((\d+)\)/i);
      if (layerMatch) {
        const layerIndex = parseInt(layerMatch[1]);

        // Look ahead for Z position in subsequent commands/comments
        let z: number | undefined;
        for (let j = i + 1; j < Math.min(i + 10, commands.length); j++) {
          const nextCommand = commands[j];

          // Check for Z in G-code command (e.g., "G1 Z0.3")
          if (nextCommand.params?.z !== undefined) {
            z = nextCommand.params.z;
            break;
          }

          // Check for Z in comment (e.g., "; layer_z = 0.3") - handle malformed values
          if (nextCommand.comment) {
            const zMatch = nextCommand.comment.match(/layer_z = ([-\d.]+)/i);
            if (zMatch) {
              z = parseFloat(zMatch[1]);
              break;
            }
          }
        }

        // Calculate height from previous layer if available
        let height: number | undefined;
        if (layers.length > 0 && layers[layers.length - 1].z !== undefined && z !== undefined) {
          height = Math.round((z - layers[layers.length - 1].z!) * 10000) / 10000; // Round to avoid floating point precision issues
        }

        layers.push({
          layerIndex,
          z,
          height,
          lineIndex: i
        });
      }

      // Alternative format: "; layer_z = 0.3" without explicit layer number - only if no move to next layer format
      const zOnlyMatch = command.comment.match(/layer_z = ([-\d.]+)/i);
      if (zOnlyMatch && !hasMoveToNextLayer) {
        const z = parseFloat(zOnlyMatch[1]);

        // Calculate height from previous layer if available
        let height: number | undefined;
        if (layers.length > 0 && layers[layers.length - 1].z !== undefined) {
          height = Math.round((z - layers[layers.length - 1].z!) * 10000) / 10000; // Round to avoid floating point precision issues
        }

        layers.push({
          layerIndex: layers.length,
          z,
          height,
          lineIndex: i
        });
      }
    }

    return layers;
  }
}
