import { GCodeCommand } from './gcode-parser';
import { SlicerMetadataParser, LayerMetadata } from './metadata-parser-base';

export class Slic3rMetadataParser extends SlicerMetadataParser {
  readonly slicerName = 'Slic3r';

  readonly identificationPatterns = [
    /Generated by Slic3r/i,
    /Slic3r \d+\./i,
    /^move to next layer \(\d+\)/i,
    /^layer_z = [\d.-]+/i,
    /Slic3r PE/i
  ];

  parseLayerMetadata(commands: GCodeCommand[]): LayerMetadata[] {
    const layers: LayerMetadata[] = [];
    let hasMoveToNextLayer: boolean | null = null;

    for (let i = 0; i < commands.length; i++) {
      const { comment } = commands[i];
      if (!comment) continue;

      const layerMatch = comment.match(/^move to next layer \((\d+)\)/i);
      if (layerMatch) {
        hasMoveToNextLayer = true;
        const layerIndex = parseInt(layerMatch[1]);

        let z: number | undefined;
        for (let j = i + 1; j < Math.min(i + 10, commands.length); j++) {
          const next = commands[j];
          if (next.params?.z !== undefined) {
            z = next.params.z;
            break;
          }
          if (next.comment) {
            const zMatch = next.comment.match(/^layer_z = ([-\d.]+)/i);
            if (zMatch) {
              z = parseFloat(zMatch[1]);
              break;
            }
          }
        }

        const prev = layers[layers.length - 1];
        const height =
          prev?.z !== undefined && z !== undefined
            ? Math.round((z - prev.z) * 10000) / 10000
            : undefined;
        layers.push({ layerIndex, z, height, lineIndex: i });
        continue;
      }

      if (hasMoveToNextLayer !== true) {
        const zMatch = comment.match(/^layer_z = ([-\d.]+)/i);
        if (zMatch) {
          hasMoveToNextLayer = false;
          const z = parseFloat(zMatch[1]);
          const prev = layers[layers.length - 1];
          const height =
            prev?.z !== undefined ? Math.round((z - prev.z) * 10000) / 10000 : undefined;
          layers.push({ layerIndex: layers.length, z, height, lineIndex: i });
        }
      }
    }

    return layers;
  }
}
