import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { GCodePreview } from '../gcode-preview';

// Keep parsing, interpretation, scene management and geometry real; only replace
// the GPU renderer so this reproduction runs without a browser.
vi.mock('three', async (importOriginal) => {
  const actual = await importOriginal<typeof import('three')>();
  return {
    ...actual,
    WebGLRenderer: class {
      domElement: HTMLCanvasElement;
      localClippingEnabled = false;
      setPixelRatio = vi.fn();
      setSize = vi.fn();
      render = vi.fn();
      dispose = vi.fn();
      constructor(opts: { canvas: HTMLCanvasElement }) {
        this.domElement = opts.canvas;
      }
    }
  };
});

let preview: GCodePreview | undefined;
beforeEach(() => {
  localStorage.clear();
  vi.spyOn(console, 'debug').mockImplementation(() => undefined);
  vi.spyOn(console, 'info').mockImplementation(() => undefined);
});
afterEach(() => {
  preview?.dispose();
  preview = undefined;
  vi.restoreAllMocks();
});

function canvas(): HTMLCanvasElement {
  const element = document.createElement('canvas');
  Object.defineProperties(element, {
    offsetWidth: { value: 640 },
    offsetHeight: { value: 480 }
  });
  return element;
}

const chunks = [
  '; generated by PrusaSlicer 2.9.2\n;LAYER_CHANGE\n',
  ';Z:0.2\n;HEIGHT:0.2\nG0 X0 Y0 Z0.2\nG1 X10 E1\n' + ';LAYER_CHANGE\n;Z:0.4\n;HEIGHT:0.2\nG0 Z0.4\nG1 X20 E1\n'
];

for (const mode of ['whole file', 'split layer comment'] as const) {
  test(mode + ' preserves both layer heights and their extrusion paths', async () => {
    preview = new GCodePreview({ canvas: canvas(), buildVolume: { x: 200, y: 200, z: 200 } });
    const input = mode === 'whole file' ? [chunks.join('')] : chunks;
    const stream = new ReadableStream<string>({
      start(controller) {
        input.forEach((chunk) => controller.enqueue(chunk));
        controller.close();
      }
    });
    await preview.processGCodeStream(stream, { render: false });

    expect.soft(preview.parser.metadata.layerMetadata?.map(({ z, height }) => ({ z, height }))).toEqual([
      { z: 0.2, height: 0.2 },
      { z: 0.4, height: 0.2 }
    ]);
    expect(preview.job.layers.map((layer) => ({ z: layer.z, paths: layer.paths.length }))).toEqual([
      { z: 0.2, paths: 2 },
      { z: 0.4, paths: 1 }
    ]);
  });
}
