import { test, expect } from 'vitest';
import { GCodeCommand } from '../../../parser/gcode-parser';
import { setInchUnits, setMillimeterUnits } from '../../../interpreter/commands';
import { Job } from '../../../job';

test('G20 sets the units to inches', () => {
  const command = new GCodeCommand('G20', 'g20', {});
  const job = new Job();

  setInchUnits(command, job);

  expect(job.state.units).toEqual('in');
});

test('G21 sets the units to millimeters', () => {
  const command = new GCodeCommand('G21', 'g21', {});
  const job = new Job();

  setMillimeterUnits(command, job);

  expect(job.state.units).toEqual('mm');
});

import { Parser } from '../../../parser/gcode-parser';
import { Interpreter } from '../../../interpreter';

function run(gcode: string) {
  return new Interpreter().execute(new Parser().parseGCode(gcode).commands);
}

test.each(['M82', 'M83'])('normalizes linear moves, E-only moves and G92 in %s', (mode) => {
  const job = run(`G20\n${mode}\nG28\nG1 X1 Y2 Z3 E1\nG1 E-1\nG92 X2 Y3 Z4 E2\nG1 X3 Y4 Z5 E3`);
  expect(job.state.x).toBeCloseTo(50.8);
  expect(job.state.y).toBeCloseTo(76.2);
  expect(job.state.z).toBeCloseTo(101.6);
  expect(job.state.e).toBeCloseTo(mode === 'M82' ? 76.2 : 127);
});

test('unit switches preserve stored coordinates and omitted axes', () => {
  const job = run('G20\nG28\nG1 X1 Y2 Z3 E1\nG21\nG1 X50.8 E50.8\nG92 X0 E0\nG20\nG1 X1 E1');
  expect(job.state.x).toBeCloseTo(76.2);
  expect(job.state.y).toBeCloseTo(50.8);
  expect(job.state.z).toBeCloseTo(76.2);
  expect(job.stats.extrusionDistance).toBeCloseTo(76.2);
  expect(job.state.e).toBeCloseTo(25.4);
});

test.each(['G2 X2 Y0 Z1 I1 J0 E2', 'G3 X2 Y0 Z1 R1 E2'])('inch and mm arcs have identical geometry: %s', (arc) => {
  const inch = run(`G20\nG28\n${arc}`);
  const mmArc = arc.replace(/([XYZIJRE])(-?\d+)/g, (_, word, value) => `${word}${Number(value) * 25.4}`);
  const mm = run(`G21\nG28\n${mmArc}`);
  expect(inch.paths.map((path) => path.vertices)).toEqual(mm.paths.map((path) => path.vertices));
  expect(inch.boundingBox).toEqual(mm.boundingBox);
  expect(inch.stats.extrusionDistance).toBeCloseTo(50.8);
});

test.each(['G31', 'G38.2', 'G38.3', 'G38.4', 'G38.5'])('normalizes %s targets and preserves Z0 contact', (probe) => {
  const job = run(`G20\nG28\nG1 Z1\n${probe} X2 Y3 Z-1`);
  expect(job.state.x).toBeCloseTo(50.8);
  expect(job.state.y).toBeCloseTo(76.2);
  expect(job.state.z).toBe(0);
  const unknown = run(`G20\n${probe} Z-1`);
  expect(unknown.state.z).toBeCloseTo(-25.4);
});

test('slicer dimensions remain millimeters in inch mode', () => {
  const parser = new Parser();
  const parsed = parser.parseGCode('; generated by PrusaSlicer\nG20\n;WIDTH:0.45\n;HEIGHT:0.2\nG28\nG1 X1 E1');
  const job = new Job();
  job.metadata = parser.metadata;
  new Interpreter().execute(parsed.commands, job);
  expect(job.state.extrusionWidth).toBe(0.45);
  expect(job.state.lineHeight).toBe(0.2);
});
