import { test, expect } from 'vitest';
import { PrusaSlicerMetadataParser } from '../../parser/prusa-slicer-parser';
import { GCodeCommand } from '../../parser/gcode-parser';

function createCommand(src: string, comment?: string): GCodeCommand {
  return new GCodeCommand(src, 'g1', {}, comment);
}

test('PrusaSlicer parser can identify PrusaSlicer gcode', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [
    createCommand('; generated by PrusaSlicer 2.9.2', 'generated by PrusaSlicer 2.9.2'),
    createCommand('G1 X0 Y0')
  ];

  expect(parser.canParse(commands)).toBe(true);
});

test('PrusaSlicer parser can identify LAYER_CHANGE comments', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'), createCommand('G1 X0 Y0')];

  expect(parser.canParse(commands)).toBe(true);
});

test('PrusaSlicer parser rejects non-PrusaSlicer gcode', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [createCommand('; Generated with Cura', 'Generated with Cura'), createCommand('G1 X0 Y0')];

  expect(parser.canParse(commands)).toBe(false);
});

test('PrusaSlicer parser extracts single layer metadata', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'),
    createCommand(';Z:0.3', 'Z:0.3'),
    createCommand(';HEIGHT:0.3', 'HEIGHT:0.3'),
    createCommand('G1 X0 Y0 Z0.3 E1')
  ];

  const layers = parser.parseLayerMetadata(commands);

  expect(layers).toHaveLength(1);
  expect(layers[0]).toEqual({
    layerIndex: 0,
    z: 0.3,
    height: 0.3,
    lineIndex: 0
  });
});

test('PrusaSlicer parser extracts multiple layer metadata', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'),
    createCommand(';Z:0.3', 'Z:0.3'),
    createCommand(';HEIGHT:0.3', 'HEIGHT:0.3'),
    createCommand('G1 X0 Y0 Z0.3 E1'),
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'),
    createCommand(';Z:0.6', 'Z:0.6'),
    createCommand(';HEIGHT:0.3', 'HEIGHT:0.3'),
    createCommand('G1 X10 Y10 Z0.6 E2')
  ];

  const layers = parser.parseLayerMetadata(commands);

  expect(layers).toHaveLength(2);
  expect(layers[0]).toEqual({
    layerIndex: 0,
    z: 0.3,
    height: 0.3,
    lineIndex: 0
  });
  expect(layers[1]).toEqual({
    layerIndex: 1,
    z: 0.6,
    height: 0.3,
    lineIndex: 4
  });
});

test('PrusaSlicer parser handles missing Z or HEIGHT values', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'),
    createCommand(';Z:0.3', 'Z:0.3'),
    createCommand('G1 X0 Y0 Z0.3 E1'),
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'),
    createCommand(';HEIGHT:0.3', 'HEIGHT:0.3'),
    createCommand('G1 X10 Y10 Z0.6 E2')
  ];

  const layers = parser.parseLayerMetadata(commands);

  expect(layers).toHaveLength(2);
  expect(layers[0]).toEqual({
    layerIndex: 0,
    z: 0.3,
    lineIndex: 0
  });
  expect(layers[1]).toEqual({
    layerIndex: 1,
    height: 0.3,
    lineIndex: 3
  });
});

test('PrusaSlicer parser handles malformed Z and HEIGHT values', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'),
    createCommand(';Z:invalid', 'Z:invalid'),
    createCommand(';HEIGHT:also-invalid', 'HEIGHT:also-invalid'),
    createCommand('G1 X0 Y0 Z0.3 E1')
  ];

  const layers = parser.parseLayerMetadata(commands);

  expect(layers).toHaveLength(1);
  expect(layers[0]).toEqual({
    layerIndex: 0,
    lineIndex: 0
  });
});

test('PrusaSlicer parser returns empty array when no LAYER_CHANGE found', () => {
  const parser = new PrusaSlicerMetadataParser();

  const commands = [createCommand('G1 X0 Y0'), createCommand('G1 X10 Y10')];

  const layers = parser.parseLayerMetadata(commands);

  expect(layers).toHaveLength(0);
});
