import { PrusaFamilyMetadataParser } from '../../parser/prusa-family-parser';
import { GCodeCommand } from '../../parser/gcode-parser';

describe('PrusaFamilyMetadataParser', () => {
  let parser: PrusaFamilyMetadataParser;

  beforeEach(() => {
    parser = new PrusaFamilyMetadataParser();
  });

  describe('canParse', () => {
    it('should identify SuperSlicer gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; generated by SuperSlicer 2.3.57 on 2023-01-01 at 12:00:00 UTC' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify OrcaSlicer gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; generated by OrcaSlicer 1.7.0 on 2023-06-15 at 14:30:00 UTC' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify BambuStudio gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; generated by BambuStudio 1.8.4.50' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify Bambu Lab references', () => {
      const commands: GCodeCommand[] = [{ comment: '; Bambu Lab A1 mini' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by layer change markers', () => {
      const commands: GCodeCommand[] = [{ comment: ';LAYER_CHANGE' }, { comment: ';Z:0.2' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by before/after layer change markers', () => {
      const commands: GCodeCommand[] = [{ comment: ';BEFORE_LAYER_CHANGE' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by a standalone WIDTH comment', () => {
      const commands: GCodeCommand[] = [{ comment: 'WIDTH:0.45' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by a standalone HEIGHT comment', () => {
      const commands: GCodeCommand[] = [{ comment: 'HEIGHT:0.16' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should not identify non-Prusa-family gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; Cura_SteamEngine 4.8.0' }, { comment: '; LAYER:0' }];
      expect(parser.canParse(commands)).toBe(false);
    });

    it('should not mistake Cura layer-height settings for dimension comments', () => {
      const commands: GCodeCommand[] = [{ comment: 'Layer height: 0.2' }];
      expect(parser.canParse(commands)).toBe(false);
    });

    it('should handle empty commands', () => {
      expect(parser.canParse([])).toBe(false);
    });
  });

  describe('parseLayerMetadata', () => {
    it('should parse single layer with complete metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.2' },
        { comment: 'HEIGHT:0.2' },
        { gcode: 'G1 X10 Y20 Z0.2 E1' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: 0.2,
        lineIndex: 0
      });
    });

    it('should parse multiple layers', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.2' },
        { comment: 'HEIGHT:0.2' },
        { gcode: 'G1 X10 Y20' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.4' },
        { comment: 'HEIGHT:0.2' },
        { gcode: 'G1 X20 Y30' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2);

      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: 0.2,
        lineIndex: 0
      });

      expect(result[1]).toEqual({
        layerIndex: 1,
        z: 0.4,
        height: 0.2,
        lineIndex: 4
      });
    });

    it('should handle explicit layer indices', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'LAYER:5' },
        { comment: 'Z:1.0' },
        { comment: 'HEIGHT:0.2' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].layerIndex).toBe(5);
    });

    it('should handle missing Z values', () => {
      const commands: GCodeCommand[] = [{ comment: 'LAYER_CHANGE' }, { comment: 'HEIGHT:0.2' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBeUndefined();
      expect(result[0].height).toBe(0.2);
    });

    it('should handle missing height values', () => {
      const commands: GCodeCommand[] = [{ comment: 'LAYER_CHANGE' }, { comment: 'Z:0.2' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(0.2);
      expect(result[0].height).toBeUndefined();
    });

    it('should handle SuperSlicer-style metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: '; generated by SuperSlicer 2.4.58.4 on 2023-12-01 at 10:15:00 UTC' },
        { comment: 'BEFORE_LAYER_CHANGE' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.3' },
        { comment: 'HEIGHT:0.3' },
        { gcode: 'G1 F1800' },
        { comment: 'AFTER_LAYER_CHANGE' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.3,
        height: 0.3,
        lineIndex: 2
      });
    });

    it('should handle OrcaSlicer-style metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: '; generated by OrcaSlicer 1.8.1 on 2024-01-15 at 16:45:00 UTC' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.25' },
        { comment: 'HEIGHT:0.25' },
        { gcode: 'G1 X0 Y0 Z0.25' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.25,
        height: 0.25,
        lineIndex: 1
      });
    });

    it('should handle BambuStudio-style metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: '; generated by BambuStudio 1.8.4.50' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.28' },
        { comment: 'HEIGHT:0.28' },
        { gcode: 'G1 Z0.28' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.28,
        height: 0.28,
        lineIndex: 1
      });
    });

    it('should handle malformed numeric values', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:invalid' },
        { comment: 'HEIGHT:also-invalid' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBeUndefined();
      expect(result[0].height).toBeUndefined();
    });

    it('should return empty array for no layer changes', () => {
      const commands: GCodeCommand[] = [{ gcode: 'G1 X10 Y20' }, { comment: '; some random comment' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(0);
    });

    it('should handle negative Z values', () => {
      const commands: GCodeCommand[] = [{ comment: 'LAYER_CHANGE' }, { comment: 'Z:-0.1' }, { comment: 'HEIGHT:0.2' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(-0.1);
    });

    it('should handle decimal values correctly', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:12.345' },
        { comment: 'HEIGHT:0.199' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(12.345);
      expect(result[0].height).toBe(0.199);
    });
  });

  describe('parseExtrusionDimensions', () => {
    it('should report WIDTH and HEIGHT comments as line-indexed events', () => {
      const commands: GCodeCommand[] = [
        { comment: 'WIDTH:0.45' },
        { gcode: 'G1 X10 Y20' },
        { comment: 'HEIGHT:0.16' },
        { gcode: 'G1 X20 Y20' }
      ];

      const result = parser.parseExtrusionDimensions(commands);
      expect(result).toEqual([
        { width: 0.45, lineIndex: 0 },
        { height: 0.16, lineIndex: 2 }
      ]);
    });

    it('should tolerate whitespace around the colon and value', () => {
      const commands: GCodeCommand[] = [{ comment: 'WIDTH : 0.33' }, { comment: 'HEIGHT:  0.11 ' }];

      const result = parser.parseExtrusionDimensions(commands);
      expect(result).toEqual([
        { width: 0.33, lineIndex: 0 },
        { height: 0.11, lineIndex: 1 }
      ]);
    });

    it('should report a HEIGHT inside a LAYER_CHANGE block too', () => {
      // There it doubles as the layer's height and as the line height of the
      // paths that follow — which is how adaptive layer height reaches paths.
      const commands: GCodeCommand[] = [{ comment: 'LAYER_CHANGE' }, { comment: 'Z:0.36' }, { comment: 'HEIGHT:0.16' }];

      expect(parser.parseExtrusionDimensions(commands)).toEqual([{ height: 0.16, lineIndex: 2 }]);
      expect(parser.parseLayerMetadata(commands)[0].height).toBe(0.16);
    });

    it.each([
      ['a non-numeric value', 'WIDTH:abc'],
      ['an empty value', 'WIDTH:'],
      ['zero', 'WIDTH:0'],
      ['a negative value', 'WIDTH:-0.4'],
      ['a non-finite value', 'WIDTH:1e999'],
      ['trailing junk after the number', 'WIDTH:0.45mm'],
      ['a lowercase key, which is not the dialect', 'width:0.5'],
      ['a prefixed key', 'LAYER_HEIGHT:0.15'],
      ['an unrelated comment', 'TYPE:External perimeter']
    ])('should ignore %s', (_name, comment) => {
      expect(parser.parseExtrusionDimensions([{ comment }])).toEqual([]);
    });

    it('should skip commands without comments', () => {
      const commands: GCodeCommand[] = [{ gcode: 'G1 X10 Y20' }, { comment: 'WIDTH:0.45' }];

      expect(parser.parseExtrusionDimensions(commands)).toEqual([{ width: 0.45, lineIndex: 1 }]);
    });
  });

  // Comments arrive pre-trimmed from parseCommand, so these hand-built
  // comments deliberately carry no leading '; '.
  describe('detectSlicerName', () => {
    it('should report PrusaSlicer when the header names it', () => {
      const commands: GCodeCommand[] = [
        { comment: 'generated by PrusaSlicer 2.7.1+win64 on 2024-01-01 at 10:00:00 UTC' }
      ];
      expect(parser.detectSlicerName(commands)).toBe('PrusaSlicer');
    });

    it('should report SuperSlicer when the header names it', () => {
      const commands: GCodeCommand[] = [{ comment: 'generated by SuperSlicer 2.4.58.4 on 2023-12-01 at 10:15:00 UTC' }];
      expect(parser.detectSlicerName(commands)).toBe('SuperSlicer');
    });

    it('should report OrcaSlicer when the header names it', () => {
      const commands: GCodeCommand[] = [{ comment: 'generated by OrcaSlicer 1.9.0' }];
      expect(parser.detectSlicerName(commands)).toBe('OrcaSlicer');
    });

    it('should report BambuStudio when the header names it', () => {
      const commands: GCodeCommand[] = [{ comment: 'generated by BambuStudio 1.8.4.50' }];
      expect(parser.detectSlicerName(commands)).toBe('BambuStudio');
    });

    it('should fall back to PrusaFamily when only layer change markers exist', () => {
      const commands: GCodeCommand[] = [{ comment: 'LAYER_CHANGE' }, { comment: 'Z:0.2' }, { comment: 'HEIGHT:0.2' }];
      expect(parser.detectSlicerName(commands)).toBe('PrusaFamily');
    });

    it('should only sample the first 200 comments for the header', () => {
      const filler: GCodeCommand[] = Array.from({ length: 250 }, (_, i) => ({ comment: `setting ${i} = ${i}` }));
      const commands: GCodeCommand[] = [...filler, { comment: 'generated by OrcaSlicer 1.9.0' }];
      expect(parser.detectSlicerName(commands)).toBe('PrusaFamily');
    });
  });
});
