import { PrusaFamilyMetadataParser } from '../../parser/prusa-family-parser';
import { GCodeCommand } from '../../parser/gcode-parser';

describe('PrusaFamilyMetadataParser', () => {
  let parser: PrusaFamilyMetadataParser;

  beforeEach(() => {
    parser = new PrusaFamilyMetadataParser();
  });

  describe('canParse', () => {
    it('should identify SuperSlicer gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; generated by SuperSlicer 2.3.57 on 2023-01-01 at 12:00:00 UTC' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify OrcaSlicer gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; generated by OrcaSlicer 1.7.0 on 2023-06-15 at 14:30:00 UTC' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify BambuStudio gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; generated by BambuStudio 1.8.4.50' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify Bambu Lab references', () => {
      const commands: GCodeCommand[] = [{ comment: '; Bambu Lab A1 mini' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by layer change markers', () => {
      const commands: GCodeCommand[] = [{ comment: ';LAYER_CHANGE' }, { comment: ';Z:0.2' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by before/after layer change markers', () => {
      const commands: GCodeCommand[] = [{ comment: ';BEFORE_LAYER_CHANGE' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should not identify non-Prusa-family gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; Cura_SteamEngine 4.8.0' }, { comment: '; LAYER:0' }];
      expect(parser.canParse(commands)).toBe(false);
    });

    it('should handle empty commands', () => {
      expect(parser.canParse([])).toBe(false);
    });
  });

  describe('parseLayerMetadata', () => {
    it('should parse single layer with complete metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.2' },
        { comment: 'HEIGHT:0.2' },
        { gcode: 'G1 X10 Y20 Z0.2 E1' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: 0.2,
        lineIndex: 0
      });
    });

    it('should parse multiple layers', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.2' },
        { comment: 'HEIGHT:0.2' },
        { gcode: 'G1 X10 Y20' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.4' },
        { comment: 'HEIGHT:0.2' },
        { gcode: 'G1 X20 Y30' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2);

      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: 0.2,
        lineIndex: 0
      });

      expect(result[1]).toEqual({
        layerIndex: 1,
        z: 0.4,
        height: 0.2,
        lineIndex: 4
      });
    });

    it('should handle explicit layer indices', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'LAYER:5' },
        { comment: 'Z:1.0' },
        { comment: 'HEIGHT:0.2' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].layerIndex).toBe(5);
    });

    it('should handle missing Z values', () => {
      const commands: GCodeCommand[] = [{ comment: 'LAYER_CHANGE' }, { comment: 'HEIGHT:0.2' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBeUndefined();
      expect(result[0].height).toBe(0.2);
    });

    it('should handle missing height values', () => {
      const commands: GCodeCommand[] = [{ comment: 'LAYER_CHANGE' }, { comment: 'Z:0.2' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(0.2);
      expect(result[0].height).toBeUndefined();
    });

    it('should handle SuperSlicer-style metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: '; generated by SuperSlicer 2.4.58.4 on 2023-12-01 at 10:15:00 UTC' },
        { comment: 'BEFORE_LAYER_CHANGE' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.3' },
        { comment: 'HEIGHT:0.3' },
        { gcode: 'G1 F1800' },
        { comment: 'AFTER_LAYER_CHANGE' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.3,
        height: 0.3,
        lineIndex: 2
      });
    });

    it('should handle OrcaSlicer-style metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: '; generated by OrcaSlicer 1.8.1 on 2024-01-15 at 16:45:00 UTC' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.25' },
        { comment: 'HEIGHT:0.25' },
        { gcode: 'G1 X0 Y0 Z0.25' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.25,
        height: 0.25,
        lineIndex: 1
      });
    });

    it('should handle BambuStudio-style metadata', () => {
      const commands: GCodeCommand[] = [
        { comment: '; generated by BambuStudio 1.8.4.50' },
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:0.28' },
        { comment: 'HEIGHT:0.28' },
        { gcode: 'G1 Z0.28' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.28,
        height: 0.28,
        lineIndex: 1
      });
    });

    it('should handle malformed numeric values', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:invalid' },
        { comment: 'HEIGHT:also-invalid' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBeUndefined();
      expect(result[0].height).toBeUndefined();
    });

    it('should return empty array for no layer changes', () => {
      const commands: GCodeCommand[] = [{ gcode: 'G1 X10 Y20' }, { comment: '; some random comment' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(0);
    });

    it('should handle negative Z values', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:-0.1' },
        { comment: 'HEIGHT:0.2' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(-0.1);
    });

    it('should handle decimal values correctly', () => {
      const commands: GCodeCommand[] = [
        { comment: 'LAYER_CHANGE' },
        { comment: 'Z:12.345' },
        { comment: 'HEIGHT:0.199' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(12.345);
      expect(result[0].height).toBe(0.199);
    });
  });
});
