import { Simplify3DMetadataParser } from '../../parser/simplify3d-parser';
import { GCodeCommand } from '../../parser/gcode-parser';

describe('Simplify3DMetadataParser', () => {
  let parser: Simplify3DMetadataParser;

  beforeEach(() => {
    parser = new Simplify3DMetadataParser();
  });

  describe('canParse', () => {
    it('should identify Simplify3D gcode by generator comment', () => {
      const commands: GCodeCommand[] = [{ comment: '; Generated by Simplify3D(R) Version 4.1.2' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify Simplify3D gcode by software name', () => {
      const commands: GCodeCommand[] = [{ comment: '; Simplify3D Settings File' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by layer format', () => {
      const commands: GCodeCommand[] = [{ comment: '; layer 1, Z = 0.2' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by layer count comment', () => {
      const commands: GCodeCommand[] = [{ comment: '; Layer count: 200' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should not identify non-Simplify3D gcode', () => {
      const commands: GCodeCommand[] = [{ comment: '; generated by PrusaSlicer 2.4.0' }, { comment: '; LAYER_CHANGE' }];
      expect(parser.canParse(commands)).toBe(false);
    });

    it('should handle empty commands', () => {
      expect(parser.canParse([])).toBe(false);
    });
  });

  describe('parseLayerMetadata', () => {
    it('should parse single layer with complete metadata', () => {
      const commands: GCodeCommand[] = [{ comment: '; layer 1, Z = 0.2' }, { gcode: 'G1 X10 Y20 Z0.2 E1' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 1,
        z: 0.2,
        height: undefined, // No previous layer to calculate from
        lineIndex: 0
      });
    });

    it('should parse multiple layers and calculate heights', () => {
      const commands: GCodeCommand[] = [
        { comment: '; layer 0, Z = 0.2' },
        { gcode: 'G1 X10 Y20' },
        { comment: '; layer 1, Z = 0.4' },
        { gcode: 'G1 X20 Y30' },
        { comment: '; layer 2, Z = 0.6' },
        { gcode: 'G1 X30 Y40' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(3);

      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: undefined, // First layer has no height calculation
        lineIndex: 0
      });

      expect(result[1]).toEqual({
        layerIndex: 1,
        z: 0.4,
        height: 0.2, // 0.4 - 0.2
        lineIndex: 2
      });

      expect(result[2]).toEqual({
        layerIndex: 2,
        z: 0.6,
        height: 0.2, // 0.6 - 0.4
        lineIndex: 4
      });
    });

    it('should handle alternative Layer Z format', () => {
      const commands: GCodeCommand[] = [
        { comment: '; Layer Z = 0.3' },
        { gcode: 'G1 X10 Y20' },
        { comment: '; Layer Z = 0.6' },
        { gcode: 'G1 X20 Y30' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2);

      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.3,
        height: undefined,
        lineIndex: 0
      });

      expect(result[1]).toEqual({
        layerIndex: 1,
        z: 0.6,
        height: 0.3, // 0.6 - 0.3
        lineIndex: 2
      });
    });

    it('should prioritize standard format over alternative', () => {
      const commands: GCodeCommand[] = [
        { comment: '; layer 5, Z = 1.0' }, // Should use this
        { comment: '; Layer Z = 1.0' } // Should ignore this (because layerMatch exists)
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].layerIndex).toBe(5); // Uses explicit layer number
    });

    it('should handle negative Z values', () => {
      const commands: GCodeCommand[] = [{ comment: '; layer 0, Z = -0.1' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(-0.1);
    });

    it('should handle decimal values correctly', () => {
      const commands: GCodeCommand[] = [{ comment: '; layer 10, Z = 12.345' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(12.345);
      expect(result[0].layerIndex).toBe(10);
    });

    it('should handle case insensitive matching', () => {
      const commands: GCodeCommand[] = [{ comment: '; LAYER 1, Z = 0.2' }, { comment: '; Layer 2, z = 0.4' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2);
      expect(result[0].layerIndex).toBe(1);
      expect(result[1].layerIndex).toBe(2);
    });

    it('should return empty array for no layer comments', () => {
      const commands: GCodeCommand[] = [{ gcode: 'G1 X10 Y20' }, { comment: '; some random comment' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(0);
    });

    it('should handle malformed layer comments gracefully', () => {
      const commands: GCodeCommand[] = [{ comment: '; layer invalid, Z = 0.2' }, { comment: '; layer 1, Z = invalid' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2); // Both match the relaxed regex
      expect(result[0].layerIndex).toBeNaN(); // parseInt('invalid') = NaN
      expect(result[0].z).toBe(0.2); // parseFloat('0.2') = 0.2
      expect(result[1].layerIndex).toBe(1); // parseInt('1') = 1
      expect(result[1].z).toBeNaN(); // parseFloat('invalid') = NaN
    });

    it('should handle typical Simplify3D header format', () => {
      const commands: GCodeCommand[] = [
        { comment: '; Generated by Simplify3D(R) Version 4.1.2' },
        { comment: '; Layer count: 150' },
        { comment: '; layer 1, Z = 0.2' },
        { gcode: 'G1 F1800' },
        { comment: '; layer 2, Z = 0.4' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2);
      expect(result[0]).toEqual({
        layerIndex: 1,
        z: 0.2,
        height: undefined,
        lineIndex: 2
      });
      expect(result[1]).toEqual({
        layerIndex: 2,
        z: 0.4,
        height: 0.2,
        lineIndex: 4
      });
    });
  });
});
