import { Slic3rMetadataParser } from '../../parser/slic3r-parser';
import { GCodeCommand } from '../../parser/gcode-parser';

describe('Slic3rMetadataParser', () => {
  let parser: Slic3rMetadataParser;

  beforeEach(() => {
    parser = new Slic3rMetadataParser();
  });

  describe('canParse', () => {
    it('should identify Slic3r gcode by generator comment', () => {
      const commands: GCodeCommand[] = [{ comment: 'Generated by Slic3r 1.3.0 on 2023-01-01 at 12:00:00' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify Slic3r by version comment', () => {
      const commands: GCodeCommand[] = [{ comment: 'Slic3r 1.2.9' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify Slic3r PE (Prusa Edition)', () => {
      const commands: GCodeCommand[] = [{ comment: 'Slic3r PE 1.41.3+linux-x64 on 2023-06-15 at 14:30:00 UTC' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by move to next layer format', () => {
      const commands: GCodeCommand[] = [{ comment: 'move to next layer (1)' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should identify by layer_z comment', () => {
      const commands: GCodeCommand[] = [{ comment: 'layer_z = 0.2' }];
      expect(parser.canParse(commands)).toBe(true);
    });

    it('should not identify non-Slic3r gcode', () => {
      const commands: GCodeCommand[] = [{ comment: 'generated by PrusaSlicer 2.4.0' }, { comment: 'LAYER_CHANGE' }];
      expect(parser.canParse(commands)).toBe(false);
    });

    it('should handle empty commands', () => {
      expect(parser.canParse([])).toBe(false);
    });
  });

  describe('parseLayerMetadata', () => {
    it('should parse single layer with move to next layer format', () => {
      const commands: GCodeCommand[] = [
        { comment: 'move to next layer (1)' },
        { gcode: 'G1 X10 Y20 Z0.2 E1', params: { x: 10, y: 20, z: 0.2, e: 1 } }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 1,
        z: 0.2,
        height: undefined, // No previous layer to calculate from
        lineIndex: 0
      });
    });

    it('should parse layer with layer_z comment', () => {
      const commands: GCodeCommand[] = [
        { comment: 'move to next layer (0)' },
        { comment: 'layer_z = 0.2' },
        { gcode: 'G1 X10 Y20' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: undefined,
        lineIndex: 0
      });
    });

    it('should parse multiple layers and calculate heights', () => {
      const commands: GCodeCommand[] = [
        { comment: 'move to next layer (0)' },
        { gcode: 'G1 X10 Y20 Z0.2', params: { x: 10, y: 20, z: 0.2 } },
        { comment: 'move to next layer (1)' },
        { gcode: 'G1 X20 Y30 Z0.4', params: { x: 20, y: 30, z: 0.4 } },
        { comment: 'move to next layer (2)' },
        { gcode: 'G1 X30 Y40 Z0.6', params: { x: 30, y: 40, z: 0.6 } }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(3);

      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: undefined,
        lineIndex: 0
      });

      expect(result[1]).toEqual({
        layerIndex: 1,
        z: 0.4,
        height: 0.2, // 0.4 - 0.2
        lineIndex: 2
      });

      expect(result[2]).toEqual({
        layerIndex: 2,
        z: 0.6,
        height: 0.2, // 0.6 - 0.4
        lineIndex: 4
      });
    });

    it('should handle layer_z only format without layer numbers', () => {
      const commands: GCodeCommand[] = [
        { comment: 'layer_z = 0.3' },
        { gcode: 'G1 X10 Y20' },
        { comment: 'layer_z = 0.6' },
        { gcode: 'G1 X20 Y30' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2);

      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.3,
        height: undefined,
        lineIndex: 0
      });

      expect(result[1]).toEqual({
        layerIndex: 1,
        z: 0.6,
        height: 0.3, // 0.6 - 0.3
        lineIndex: 2
      });
    });

    it('should prioritize move to next layer over layer_z only', () => {
      const commands: GCodeCommand[] = [
        { comment: 'move to next layer (5)' },
        { comment: 'layer_z = 1.0' } // Should be ignored for layer index
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].layerIndex).toBe(5); // Uses explicit layer number from move comment
      expect(result[0].z).toBe(1.0); // Uses Z from layer_z comment
    });

    it('should look ahead for Z position in G-code commands', () => {
      const commands: GCodeCommand[] = [
        { comment: 'move to next layer (1)' },
        { gcode: 'G1 F1800' },
        { gcode: 'G1 X0 Y0' },
        { gcode: 'G1 Z0.25', params: { z: 0.25 } }, // Z found here
        { gcode: 'G1 X10 Y10' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(0.25);
    });

    it('should handle case insensitive matching', () => {
      const commands: GCodeCommand[] = [{ comment: 'MOVE TO NEXT LAYER (1)' }, { comment: 'LAYER_Z = 0.2' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].layerIndex).toBe(1);
      expect(result[0].z).toBe(0.2);
    });

    it('should handle negative Z values', () => {
      const commands: GCodeCommand[] = [{ comment: 'move to next layer (0)' }, { comment: 'layer_z = -0.1' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(-0.1);
    });

    it('should handle decimal values correctly', () => {
      const commands: GCodeCommand[] = [{ comment: 'move to next layer (10)' }, { comment: 'layer_z = 12.345' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBe(12.345);
      expect(result[0].layerIndex).toBe(10);
    });

    it('should return empty array for no layer comments', () => {
      const commands: GCodeCommand[] = [{ gcode: 'G1 X10 Y20' }, { comment: 'some random comment' }];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(0);
    });

    it('should handle missing Z position gracefully', () => {
      const commands: GCodeCommand[] = [
        { comment: 'move to next layer (1)' },
        { gcode: 'G1 X10 Y20' }, // No Z parameter
        { comment: 'some other comment' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBeUndefined();
    });

    it('should handle malformed layer comments gracefully', () => {
      // Non-digit layer numbers are rejected by the strict \d+ regex to prevent ReDoS
      const commands: GCodeCommand[] = [
        { comment: '; move to next layer (invalid)' },
        { comment: '; layer_z = invalid' }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(0); // Neither matches \d+ pattern
    });

    it('should handle typical Slic3r format', () => {
      const commands: GCodeCommand[] = [
        { comment: 'Generated by Slic3r 1.3.0 on 2023-01-01 at 12:00:00' },
        { comment: 'move to next layer (0)' },
        { comment: 'layer_z = 0.2' },
        { gcode: 'G1 F1800' },
        { comment: 'move to next layer (1)' },
        { gcode: 'G1 Z0.4', params: { z: 0.4 } }
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(2);
      expect(result[0]).toEqual({
        layerIndex: 0,
        z: 0.2,
        height: undefined,
        lineIndex: 1
      });
      expect(result[1]).toEqual({
        layerIndex: 1,
        z: 0.4,
        height: 0.2,
        lineIndex: 4
      });
    });

    it('should limit Z position lookahead to 10 commands', () => {
      const commands: GCodeCommand[] = [
        { comment: 'move to next layer (1)' },
        ...Array(12).fill({ gcode: 'G1 X0 Y0' }), // 12 commands without Z
        { gcode: 'G1 Z0.2', params: { z: 0.2 } } // Z too far away
      ];

      const result = parser.parseLayerMetadata(commands);
      expect(result).toHaveLength(1);
      expect(result[0].z).toBeUndefined(); // Should not find Z that far
    });
  });
});
