import { describe, it, expect } from 'vitest';
import { Parser } from '../../parser/gcode-parser';

// Realistic mini gcode files, formatted exactly like real slicer output:
// prose comments carry the leading '; ' real slicers emit, while structured
// markers (;LAYER_CHANGE, ;Z:, ;LAYER:n, ...) have no space after ';'.

const PRUSA_LINES = [
  '; generated by PrusaSlicer 2.7.1+win64 on 2024-01-01 at 10:00:00 UTC',
  ';',
  '; external perimeters extrusion width = 0.45mm',
  'M140 S60 ; set bed temperature',
  'M104 S215 ; set temporary nozzle temp to prevent oozing during homing',
  'G28 ; home all axes',
  'G90 ; use absolute coordinates',
  ';LAYER_CHANGE',
  ';Z:0.2',
  ';HEIGHT:0.2',
  'G1 Z0.2 F7200',
  'G1 X10 Y10 F7200',
  'G1 X20 Y10 E0.5 F1800',
  'G1 X20 Y20 E1',
  ';LAYER_CHANGE',
  ';Z:0.4',
  ';HEIGHT:0.2',
  'G1 Z0.4 F7200',
  'G1 X10 Y10 E1.5',
  'G1 X20 Y10 E2'
];
const PRUSA_GCODE = PRUSA_LINES.join('\n');

const ORCA_LINES = [
  '; generated by OrcaSlicer 1.9.0 on 2024-02-02 at 12:00:00 UTC',
  '; total filament used [g] = 1.23',
  'M140 S55 ; set bed temperature',
  'M104 S220 ; set nozzle temperature',
  'G28 ; home all axes',
  ';LAYER_CHANGE',
  ';Z:0.2',
  ';HEIGHT:0.2',
  ';LAYER:0',
  'G1 Z0.2 F9000',
  'G1 X50 Y50 F9000',
  'G1 X60 Y50 E0.8 F2400',
  ';LAYER_CHANGE',
  ';Z:0.4',
  ';HEIGHT:0.2',
  ';LAYER:1',
  'G1 Z0.4 F9000',
  'G1 X60 Y60 E1.6',
  ';LAYER_CHANGE',
  ';Z:0.6',
  ';HEIGHT:0.2',
  ';LAYER:2',
  'G1 Z0.6 F9000',
  'G1 X50 Y60 E2.4'
];
const ORCA_GCODE = ORCA_LINES.join('\n');

const CURA_LINES = [
  ';FLAVOR:Marlin',
  ';TIME:1234',
  ';Filament used: 0.123m',
  ';Layer height: 0.2',
  ';Generated with Cura_SteamEngine 5.6.0',
  'M140 S60',
  'M104 S200',
  'G28 ;Home',
  'G92 E0',
  ';LAYER_COUNT:3',
  ';LAYER:0',
  'M107',
  'G0 F6000 X100 Y100 Z0.2',
  ';TYPE:SKIRT',
  'G1 F1200 X110 Y100 E0.5',
  'G1 X110 Y110 E1.0',
  ';LAYER:1',
  'G0 F6000 X100 Y100 Z0.4',
  'G1 F1200 X110 Y100 E1.5',
  'G1 X110 Y110 E2.0',
  ';LAYER:2',
  'G0 F6000 X100 Y100 Z0.6',
  'G1 F1200 X110 Y100 E2.5',
  'G1 X110 Y110 E3.0'
];
const CURA_GCODE = CURA_LINES.join('\n');

const SIMPLIFY3D_LINES = [
  '; G-Code generated by Simplify3D(R) Version 4.1.2',
  '; Jan 1, 2024 at 10:00:00 AM',
  '; Settings Summary',
  ';   processName,Process1',
  ';   layerHeight,0.2',
  'M140 S60 ; heat bed',
  'M104 S210 T0 ; heat extruder',
  'G28 ; home all axes',
  'G90 ; absolute positioning',
  '; process Process1',
  '; layer 1, Z = 0.200',
  'G1 Z0.200 F1002',
  'G1 X10.0 Y10.0 F4800',
  'G1 X20.0 Y10.0 E0.4756 F1800',
  'G1 X20.0 Y20.0 E0.9512',
  '; layer 2, Z = 0.400',
  'G1 Z0.400 F1002',
  'G1 X10.0 Y10.0 E1.4268',
  'G1 X20.0 Y10.0 E1.9024'
];
const SIMPLIFY3D_GCODE = SIMPLIFY3D_LINES.join('\n');

const SLIC3R_LINES = [
  '; generated by Slic3r 1.3.0 on 2024-03-03 at 09:00:00 GMT',
  '; layer_height = 0.2',
  '; fill_density = 20%',
  'M140 S60 ; set bed temperature',
  'M104 S200 ; set temperature',
  'G28 ; home all axes',
  'G90 ; use absolute coordinates',
  '; move to next layer (0)',
  '; layer_z = 0.2',
  'G1 Z0.200 F7800.000',
  'G1 X10.0 Y10.0 F7800',
  'G1 X20.0 Y10.0 E1.0 F1800',
  '; move to next layer (1)',
  '; layer_z = 0.4',
  'G1 Z0.400 F7800.000',
  'G1 X20.0 Y20.0 E2.0'
];
const SLIC3R_GCODE = SLIC3R_LINES.join('\n');

describe('slicer fixtures (real-world comment formatting)', () => {
  it('parses the PrusaSlicer fixture', () => {
    const { metadata } = new Parser().parseGCode(PRUSA_GCODE);

    expect(metadata.slicerName).toBe('PrusaSlicer');
    expect(metadata.layerMetadata).toHaveLength(2);

    const [layer0, layer1] = metadata.layerMetadata!;
    expect(layer0.z).toBeCloseTo(0.2);
    expect(layer0.height).toBeCloseTo(0.2);
    expect(layer0.layerIndex).toBe(0);
    expect(layer0.lineIndex).toBe(PRUSA_LINES.indexOf(';LAYER_CHANGE'));

    expect(layer1.z).toBeCloseTo(0.4);
    expect(layer1.height).toBeCloseTo(0.2);
    expect(layer1.layerIndex).toBe(1);
    expect(layer1.lineIndex).toBe(PRUSA_LINES.indexOf(';LAYER_CHANGE', PRUSA_LINES.indexOf(';LAYER_CHANGE') + 1));
  });

  it('parses the OrcaSlicer fixture with explicit layer indices', () => {
    const { metadata } = new Parser().parseGCode(ORCA_GCODE);

    expect(metadata.slicerName).toBe('OrcaSlicer');
    expect(metadata.layerMetadata).toHaveLength(3);

    const layers = metadata.layerMetadata!;
    expect(layers[0].z).toBeCloseTo(0.2);
    expect(layers[1].z).toBeCloseTo(0.4);
    expect(layers[2].z).toBeCloseTo(0.6);
    layers.forEach((layer, i) => {
      expect(layer.height).toBeCloseTo(0.2);
      expect(layer.layerIndex).toBe(i);
    });
    expect(layers[0].lineIndex).toBe(ORCA_LINES.indexOf(';LAYER_CHANGE'));
  });

  it('parses the Cura fixture', () => {
    const { metadata } = new Parser().parseGCode(CURA_GCODE);

    expect(metadata.slicerName).toBe('Cura');
    expect(metadata.layerMetadata).toHaveLength(3);

    const layers = metadata.layerMetadata!;
    expect(layers[0].z).toBeCloseTo(0.2);
    expect(layers[1].z).toBeCloseTo(0.4);
    expect(layers[2].z).toBeCloseTo(0.6);

    // Cura derives heights from consecutive Z values: the first layer has no
    // predecessor, so its height is undefined.
    expect(layers[0].height).toBeUndefined();
    expect(layers[1].height).toBeCloseTo(0.2);
    expect(layers[2].height).toBeCloseTo(0.2);

    expect(layers.map((l) => l.layerIndex)).toEqual([0, 1, 2]);
    expect(layers[0].lineIndex).toBe(CURA_LINES.indexOf(';LAYER:0'));
    expect(layers[2].lineIndex).toBe(CURA_LINES.indexOf(';LAYER:2'));
  });

  it('parses the Simplify3D fixture', () => {
    const { metadata } = new Parser().parseGCode(SIMPLIFY3D_GCODE);

    expect(metadata.slicerName).toBe('Simplify3D');
    expect(metadata.layerMetadata).toHaveLength(2);

    const [layer0, layer1] = metadata.layerMetadata!;
    expect(layer0.z).toBeCloseTo(0.2);
    expect(layer1.z).toBeCloseTo(0.4);

    // Simplify3D numbers layers starting at 1; those explicit indices are kept.
    expect(layer0.layerIndex).toBe(1);
    expect(layer1.layerIndex).toBe(2);

    expect(layer0.height).toBeUndefined();
    expect(layer1.height).toBeCloseTo(0.2);

    expect(layer0.lineIndex).toBe(SIMPLIFY3D_LINES.indexOf('; layer 1, Z = 0.200'));
    expect(layer1.lineIndex).toBe(SIMPLIFY3D_LINES.indexOf('; layer 2, Z = 0.400'));
  });

  it('parses the Slic3r fixture', () => {
    const { metadata } = new Parser().parseGCode(SLIC3R_GCODE);

    expect(metadata.slicerName).toBe('Slic3r');
    expect(metadata.layerMetadata).toHaveLength(2);

    const [layer0, layer1] = metadata.layerMetadata!;
    expect(layer0.z).toBeCloseTo(0.2);
    expect(layer1.z).toBeCloseTo(0.4);
    expect(layer0.layerIndex).toBe(0);
    expect(layer1.layerIndex).toBe(1);

    expect(layer0.height).toBeUndefined();
    expect(layer1.height).toBeCloseTo(0.2);

    expect(layer0.lineIndex).toBe(SLIC3R_LINES.indexOf('; move to next layer (0)'));
    expect(layer1.lineIndex).toBe(SLIC3R_LINES.indexOf('; move to next layer (1)'));
  });
});

describe('chunked parsing', () => {
  it('accumulates PrusaSlicer layer metadata across chunks identically to a single-shot parse', () => {
    const single = new Parser().parseGCode(PRUSA_GCODE).metadata;

    // Split at the line boundary between layer 1 and layer 2.
    const splitAt = PRUSA_LINES.indexOf(';LAYER_CHANGE', PRUSA_LINES.indexOf(';LAYER_CHANGE') + 1);
    const chunk1 = PRUSA_LINES.slice(0, splitAt).join('\n');
    const chunk2 = PRUSA_LINES.slice(splitAt).join('\n');

    const parser = new Parser();
    parser.parseGCode(chunk1);
    const chunked = parser.parseGCode(chunk2).metadata;

    expect(chunked.slicerName).toBe('PrusaSlicer');
    // lineIndex must be file-relative (offset by the lines in chunk 1).
    expect(chunked.layerMetadata).toEqual(single.layerMetadata);
  });

  it('keeps explicit layer indices unchanged across chunks', () => {
    const single = new Parser().parseGCode(ORCA_GCODE).metadata;

    // Chunk 2 starts at the second LAYER_CHANGE: its explicit indices (1, 2)
    // no longer match their chunk-local positions (0, 1) and must be kept.
    const splitAt = ORCA_LINES.indexOf(';LAYER_CHANGE', ORCA_LINES.indexOf(';LAYER_CHANGE') + 1);
    const parser = new Parser();
    parser.parseGCode(ORCA_LINES.slice(0, splitAt).join('\n'));
    const chunked = parser.parseGCode(ORCA_LINES.slice(splitAt).join('\n')).metadata;

    expect(chunked.slicerName).toBe('OrcaSlicer');
    expect(chunked.layerMetadata).toEqual(single.layerMetadata);
  });

  // A Prusa-dialect file that omits ;HEIGHT: comments: heights are only
  // derivable from consecutive Z values, which crosses the chunk boundary.
  const NO_HEIGHT_LINES = [
    ';LAYER_CHANGE',
    ';Z:0.2',
    'G1 Z0.2 F7200',
    'G1 X10 Y10 E0.5',
    ';LAYER_CHANGE',
    ';Z:0.4',
    'G1 Z0.4 F7200',
    'G1 X20 Y10 E1',
    ';LAYER_CHANGE',
    'G1 X10 Y20 E1.5'
  ];

  it('backfills a derived height for the first layer of a chunk', () => {
    const splitAt = NO_HEIGHT_LINES.indexOf(';LAYER_CHANGE', 1);
    const parser = new Parser();
    parser.parseGCode(NO_HEIGHT_LINES.slice(0, splitAt).join('\n'));
    const { layerMetadata } = parser.parseGCode(NO_HEIGHT_LINES.slice(splitAt).join('\n')).metadata;

    expect(layerMetadata).toHaveLength(3);
    // Chunk 2's first layer knows the previous layer only in the accumulated
    // result, so its height is derived there (0.4 - 0.2).
    expect(layerMetadata![1].height).toBeCloseTo(0.2);
    // Later layers of the chunk are left to the parser: the third layer has
    // no Z at all, so no height can be derived for it.
    expect(layerMetadata![2].height).toBeUndefined();
  });

  it('skips the height backfill when the chunk opens on a layer without a Z', () => {
    const splitAt = NO_HEIGHT_LINES.lastIndexOf(';LAYER_CHANGE');
    const parser = new Parser();
    parser.parseGCode(NO_HEIGHT_LINES.slice(0, splitAt).join('\n'));
    const { layerMetadata } = parser.parseGCode(NO_HEIGHT_LINES.slice(splitAt).join('\n')).metadata;

    expect(layerMetadata).toHaveLength(3);
    expect(layerMetadata![2].z).toBeUndefined();
    expect(layerMetadata![2].height).toBeUndefined();
  });

  it('skips the height backfill when the previous layer has no Z', () => {
    const lines = [';LAYER_CHANGE', 'G1 X10 Y10 E0.5', ';LAYER_CHANGE', ';Z:0.4', 'G1 X20 Y10 E1'];
    const splitAt = lines.indexOf(';LAYER_CHANGE', 1);
    const parser = new Parser();
    parser.parseGCode(lines.slice(0, splitAt).join('\n'));
    const { layerMetadata } = parser.parseGCode(lines.slice(splitAt).join('\n')).metadata;

    expect(layerMetadata).toHaveLength(2);
    expect(layerMetadata![0].z).toBeUndefined();
    expect(layerMetadata![1].height).toBeUndefined();
  });

  it('keeps explicit Cura layer indices unchanged across chunks', () => {
    const single = new Parser().parseGCode(CURA_GCODE).metadata;

    // Split between layer 1 and layer 2.
    const splitAt = CURA_LINES.indexOf(';LAYER:2');
    const chunk1 = CURA_LINES.slice(0, splitAt).join('\n');
    const chunk2 = CURA_LINES.slice(splitAt).join('\n');

    const parser = new Parser();
    parser.parseGCode(chunk1);
    const chunked = parser.parseGCode(chunk2).metadata;

    expect(chunked.slicerName).toBe('Cura');
    expect(chunked.layerMetadata).toHaveLength(3);
    expect(single.layerMetadata).toHaveLength(3);

    chunked.layerMetadata!.forEach((layer, i) => {
      const expected = single.layerMetadata![i];
      // Explicit LAYER:n indices survive chunking unchanged, and lineIndex
      // stays file-relative.
      expect(layer.layerIndex).toBe(expected.layerIndex);
      expect(layer.lineIndex).toBe(expected.lineIndex);
      expect(layer.z).toBeCloseTo(expected.z!);
    });

    // Cura derives height from the previous layer's Z, which is chunk-local;
    // the accumulation in parseGCode backfills the first layer of a chunk from
    // the accumulated result, so chunked heights match the single-shot parse.
    expect(single.layerMetadata![2].height).toBeCloseTo(0.2);
    expect(chunked.layerMetadata![2].height).toBeCloseTo(0.2);
    // Layers wholly inside one chunk keep their heights.
    expect(chunked.layerMetadata![1].height).toBeCloseTo(0.2);
  });
});
