import { describe, it, expect } from 'vitest';
import { Parser } from '../../parser/gcode-parser';

// Realistic mini gcode files, formatted exactly like real slicer output:
// prose comments carry the leading '; ' real slicers emit, while structured
// markers (;LAYER_CHANGE, ;Z:, ;LAYER:n, ...) have no space after ';'.

const PRUSA_LINES = [
  '; generated by PrusaSlicer 2.7.1+win64 on 2024-01-01 at 10:00:00 UTC',
  ';',
  '; external perimeters extrusion width = 0.45mm',
  'M140 S60 ; set bed temperature',
  'M104 S215 ; set temporary nozzle temp to prevent oozing during homing',
  'G28 ; home all axes',
  'G90 ; use absolute coordinates',
  ';LAYER_CHANGE',
  ';Z:0.2',
  ';HEIGHT:0.2',
  'G1 Z0.2 F7200',
  'G1 X10 Y10 F7200',
  'G1 X20 Y10 E0.5 F1800',
  'G1 X20 Y20 E1',
  ';LAYER_CHANGE',
  ';Z:0.4',
  ';HEIGHT:0.2',
  'G1 Z0.4 F7200',
  'G1 X10 Y10 E1.5',
  'G1 X20 Y10 E2'
];
const PRUSA_GCODE = PRUSA_LINES.join('\n');

const ORCA_LINES = [
  '; generated by OrcaSlicer 1.9.0 on 2024-02-02 at 12:00:00 UTC',
  '; total filament used [g] = 1.23',
  'M140 S55 ; set bed temperature',
  'M104 S220 ; set nozzle temperature',
  'G28 ; home all axes',
  ';LAYER_CHANGE',
  ';Z:0.2',
  ';HEIGHT:0.2',
  ';LAYER:0',
  'G1 Z0.2 F9000',
  'G1 X50 Y50 F9000',
  'G1 X60 Y50 E0.8 F2400',
  ';LAYER_CHANGE',
  ';Z:0.4',
  ';HEIGHT:0.2',
  ';LAYER:1',
  'G1 Z0.4 F9000',
  'G1 X60 Y60 E1.6',
  ';LAYER_CHANGE',
  ';Z:0.6',
  ';HEIGHT:0.2',
  ';LAYER:2',
  'G1 Z0.6 F9000',
  'G1 X50 Y60 E2.4'
];
const ORCA_GCODE = ORCA_LINES.join('\n');

describe('slicer fixtures (real-world comment formatting)', () => {
  it('parses the PrusaSlicer fixture', () => {
    const { metadata } = new Parser().parseGCode(PRUSA_GCODE);

    expect(metadata.slicerName).toBe('PrusaSlicer');
    expect(metadata.layerMetadata).toHaveLength(2);

    const [layer0, layer1] = metadata.layerMetadata!;
    expect(layer0.z).toBeCloseTo(0.2);
    expect(layer0.height).toBeCloseTo(0.2);
    expect(layer0.layerIndex).toBe(0);
    expect(layer0.lineIndex).toBe(PRUSA_LINES.indexOf(';LAYER_CHANGE'));

    expect(layer1.z).toBeCloseTo(0.4);
    expect(layer1.height).toBeCloseTo(0.2);
    expect(layer1.layerIndex).toBe(1);
    expect(layer1.lineIndex).toBe(PRUSA_LINES.indexOf(';LAYER_CHANGE', PRUSA_LINES.indexOf(';LAYER_CHANGE') + 1));
  });

  it('parses the OrcaSlicer fixture with explicit layer indices', () => {
    const { metadata } = new Parser().parseGCode(ORCA_GCODE);

    expect(metadata.slicerName).toBe('OrcaSlicer');
    expect(metadata.layerMetadata).toHaveLength(3);

    const layers = metadata.layerMetadata!;
    expect(layers[0].z).toBeCloseTo(0.2);
    expect(layers[1].z).toBeCloseTo(0.4);
    expect(layers[2].z).toBeCloseTo(0.6);
    layers.forEach((layer, i) => {
      expect(layer.height).toBeCloseTo(0.2);
      expect(layer.layerIndex).toBe(i);
    });
    expect(layers[0].lineIndex).toBe(ORCA_LINES.indexOf(';LAYER_CHANGE'));
  });
});

describe('chunked parsing', () => {
  it('accumulates PrusaSlicer layer metadata across chunks identically to a single-shot parse', () => {
    const single = new Parser().parseGCode(PRUSA_GCODE).metadata;

    // Split at the line boundary between layer 1 and layer 2.
    const splitAt = PRUSA_LINES.indexOf(';LAYER_CHANGE', PRUSA_LINES.indexOf(';LAYER_CHANGE') + 1);
    const chunk1 = PRUSA_LINES.slice(0, splitAt).join('\n');
    const chunk2 = PRUSA_LINES.slice(splitAt).join('\n');

    const parser = new Parser();
    parser.parseGCode(chunk1);
    const chunked = parser.parseGCode(chunk2).metadata;

    expect(chunked.slicerName).toBe('PrusaSlicer');
    // lineIndex must be file-relative (offset by the lines in chunk 1).
    expect(chunked.layerMetadata).toEqual(single.layerMetadata);
  });
});
